# Generated by Django 4.2 on 2023-07-06 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('yosh', models.PositiveSmallIntegerField()),
                ('ish_vaqti', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Haydovchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=20)),
                ('kiritilgan_sana', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brend', models.CharField(max_length=100)),
                ('narx', models.IntegerField()),
                ('litr', models.CharField(max_length=100)),
                ('batafsil', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mijoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=20)),
                ('manzil', models.TextField()),
                ('qarz', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Buyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField(auto_now_add=True)),
                ('miqdor', models.CharField(max_length=100)),
                ('umumiy_narx', models.IntegerField()),
                ('mijoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.mijoz')),
                ('qabul_qilgan_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.admin')),
                ('suv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.suv')),
                ('yetkazib_berish_haydovchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.haydovchi')),
            ],
        ),
    ]
